name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Install PyInstaller
        run: |
          python -m pip install pyinstaller
        working-directory: ${{ github.workspace }}

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "img/icon.ico" --add-data "C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\customtkinter;customtkinter"  "app.py"
        working-directory: ${{ github.workspace }}
      
      - name: Check files existence
        run: |
          dir ./dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
        with:
          files: dist/*
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
