name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Install PyInstaller
        run: |
          python -m pip install pyinstaller
        working-directory: ${{ github.workspace }}

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "img/icon.ico" --add-data "C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\customtkinter;customtkinter"  "app.py"
        working-directory: ${{ github.workspace }}
      
      - name: Check files existence
        run: |
          dir ./dist

        
  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Upload exe to release
        uses: actions/upload-artifact@v2
        with:
          name: app.exe
          path: ${{ github.workspace }}\dist\app.exe

